python ./train.py --datapath "~/MY_MOT/TWL/data" \
           --benchmark coco \
           --fold 0 \
           --bsz 1 \
           --nworker 8 \
           --backbone resnet50 \
           --feature_extractor_path "~/MY_MOT/TWL/logistic_project/DCAMA/backbones/resnet50_a1h-35c100f8.pth" \
           --logpath "~/MY_MOT/TWL/logistic_project/DCAMA/log" \
           --lr 1e-4 \
           --nepoch  50 \
           --load "~/MY_MOT/TWL/logistic_project/DCAMA/checkpoint/coco-20i/resnet50_fold0.pt" \
           --nshot 2
